### ISSUE TITLE
Unable to use Column

### ISSUE THREAD

**Issue by MintyOwl** [go-pg/sharding#36]
It turns out I cannot join tables using ```Column``` method, which was possible with go-pg/pg. Any idea how to achieve that in sharded version?

Thanks, great library!

**Comment by vmihailenco** [comment]
go-pg/sharding should work just like go-pg, but joined table should be in the same shard. Can you show the code that work with go-pg and does not with go-pg/sharding?

**Comment by MintyOwl** [comment]
Code is [here](https://gist.github.com/MintyOwl/95ac0fdf0613d841cdd4fa294e36e074). 

Also I am not sure how would I use ```CreateTable``` with shard.

Thanks

**Comment by MintyOwl** [comment]
Also the example is not a classic join, but still non-trivial

**Comment by vmihailenco** [comment]
Please upgrade go-pg to v6.1.4 and try [fixed example](https://gist.github.com/vmihailenco/5f553d12173a5a9e64d8a3ba19c9b43d)

**Comment by MintyOwl** [comment]
Thanks I will check it out.

**Comment by MintyOwl** [comment]
Great, it works as expected. Thanks
